kind: PersistentVolume
apiVersion: v1
metadata:
  name: pv-jenkins
  namespace: jenkins
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  storageClassName: ""
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: "/pv/log"