apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: {{ .Values.namespace }}-{{ .Values.Deployment.label }}
  name: {{ .Values.namespace }}-{{ .Values.Deployment.name }}
  namespace: {{ .Values.namespace }}
spec:
  replicas: {{ .Values.repl.num }}
  selector:
    matchLabels:
      app: {{ .Values.namespace }}-{{ .Values.Deployment.label }}
  template:
    metadata:
      labels:
        app: {{ .Values.namespace }}-{{ .Values.temp.label }}
    spec:
      containers:
      - image: {{ .Values.image.repository }}/{{ .Values.image.name }}:{{ .Values.image.tag }}
        name: {{ .Values.namespace }}-{{ .Values.container.name }}
        imagePullPolicy: {{ .Values.container.imagePullPolicy }}
        ports:
        - containerPort: {{ .Values.container.port }}
        resources: {}
